version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "ozondb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
  ozon:
    build: ./
    env_file:
      cfg/.env
    command: ./ozon
    ports:
      - "8000:8000"
