###GetPost

POST http://localhost:4000/graphql

{
"query": "{posts(page:0,size:3){Id, AuthorId, CreatedAt, UpdatedAt, AllowComments}}"
}

###GetPostwithComment

POST http://localhost:4000/graphql

{
"query": "{postwithcomment(postid:2,page:0,size:2){PostId, PostAuthorId, PostCreatedAt, PostUpdatedAt, PostAllowComments,CommentId,CommentAuthorId, CommentParId,CommentMsg, CommentCreatedAt,CommentUpdatedAt}}"
}

###CreatePost

POST http://localhost:4000/graphql

{
"query": "{createpost(userid:1,allowcomments:true){UserId,AllowComments}}"
}

###CreateComment

POST http://localhost:4000/graphql

{
"query": "{createcomment(postid:2,userid:1,parid:1,msg:\"test2\"){PostId,UserId,ParId,Msg}}"
}"